name: complecionista
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_icons: ^1.1.0
  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2
  package_info_plus: ^1.4.2
  http: ^0.13.5
  webfeed: ^0.7.0
  dartz: ^0.10.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic

    - family: HongKong
      fonts:
        - asset: assets/fonts/hongkong/NotoSerifHK-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/hongkong/NotoSerifHK-Light.ttf
          weight: 300
        - asset: assets/fonts/hongkong/NotoSerifHK-Regular.ttf
        - asset: assets/fonts/hongkong/NotoSerifHK-Medium.ttf
          weight: 500
        - asset: assets/fonts/hongkong/NotoSerifHK-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/hongkong/NotoSerifHK-Bold.ttf
          weight: 700
        - asset: assets/fonts/hongkong/NotoSerifHK-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/hongkong/NotoSerifHK-Black.ttf
          weight: 900
